name: "ivrToolkit"
description: "An IVR toolkit library for dotNet developers wanting to write telephony applications."

url: "http://localhost:4000"


markdown: rdiscount
permalink: pretty
highlighter: rouge
ignore: "Document/API"

